## main datatype of np is ndarray

import numpy as np

In [3]:
import numpy as np

In [4]:
a1 = np.array([1,2,3])

# 

a1

In [5]:
a1

array([1, 2, 3])

In [7]:
a2 = np.array([[1,2], [3,4]])

In [8]:
a2

array([[1, 2],
       [3, 4]])

In [10]:
a2.shape

(2, 2)

In [11]:
a1.shape

(3,)

In [12]:
a1.ndim

1

In [13]:
a2.ndim

2

In [14]:
a1.size

3

In [15]:
a2.size

4

In [16]:
type(a1), type(a2)

(numpy.ndarray, numpy.ndarray)

In [19]:
zeros = np.zeros((2,3))

In [20]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])